AppBundle\Entity\Medicament:
    type: entity
    table: medicament
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
        infosComplementaires:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: infos_complementaires
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: updated_by
    manyToMany:
        ordonnance:
            targetEntity: Ordonnance
            cascade: {  }
            fetch: LAZY
            mappedBy: medicament
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
